ignore = {'ring': [
    #prefixes
    '+# to Evasion Rating',
    '+# to maximum Mana',
    '#% of Physical Attack Damage Leeched as Mana',
    '#% increased Light Radius',
    #suffixes
    '+# Life gained on Kill',
    '+#% to Lightning Resistance',
    '+#% to Chaos Resistance',
    '+#% to Cold Resistance',
    '+# to Accuracy Rating',
    '#% increased Mana Regeneration Rate',
    '+#% to Fire Resistance',
],
'amulet': [
    #prefixes
    '+# to maximum Mana',
    '#% of Physical Attack Damage Leeched as Mana',
    #suffixes
    '+# to Intelligence',
    '+# to Dexterity',
    '+#% to Global Critical Strike Multiplier',
    '+# to Strength',
    '+# Life gained on Kill',
    '+# to all Attributes',
    '+#% to Chaos Resistance',
    '+# to Accuracy Rating',
    '#% increased Mana Regeneration Rate',
],
'sceptre': [
    #prefixes
    'Adds # to # Fire Damage',
    'Adds # to # Physical Damage',
    '+# to maximum Mana',
    '+# to Accuracy Rating',
    '+#% to Cold Damage over Time Multiplier',
    'Adds # to # Chaos Damage',
    '#% increased Physical Damage',
    'Adds # to # Cold Damage',
    'Adds # to # Lightning Damage',
    '#% of Physical Attack Damage Leeched as Mana',
    #suffixes
    '+#% to Chaos Resistance',
    '#% increased Stun Duration on Enemies',
    '#% increased Cold Damage',
    '#% increased Burning Damage',
    '#% increased Fire Damage',
    '#% increased Lightning Damage',
    '+# Life gained on Kill',
    '+#% to Lightning Resistance',
    '#% chance to Ignite',
    '#% chance to Shock',
    '#% increased Critical Strike Chance',
    '#% increased Mana Regeneration Rate',
    '+#% to Cold Resistance',
    '+# to Accuracy Rating',
    '#% increased Cast Speed',
    '#% chance to Freeze',
    '#% reduced Enemy Stun Threshold',
    '+#% to Fire Resistance',
],
'wand': [
    #prefixes
    'Adds # to # Fire Damage',
    'Adds # to # Physical Damage',
    '+# to maximum Mana',
    '+# to Accuracy Rating',
    'Adds # to # Chaos Damage',
    '#% increased Physical Damage',
    '#% of Physical Attack Damage Leeched as Life',
    'Adds # to # Cold Damage',
    '+#% to Non-Ailment Chaos Damage over Time Multiplier',
    'Adds # to # Lightning Damage',
    '#% of Physical Attack Damage Leeched as Mana',
    #suffixes
    '+#% to Chaos Resistance',
    '#% increased Stun Duration on Enemies',
    '#% increased Cold Damage',
    '#% increased Burning Damage',
    '#% increased Fire Damage',
    '#% increased Attack Speed',
    '#% increased Lightning Damage',
    '+# Life gained on Kill',
    '+#% to Lightning Resistance',
    '#% chance to Ignite',
    '#% chance to Shock',
    '#% increased Critical Strike Chance',
    '#% increased Mana Regeneration Rate',
    '+#% to Cold Resistance',
    '+# to Accuracy Rating',
    '#% increased Cast Speed',
    '#% chance to Freeze',
    '+#% to Fire Resistance',
],
'boots': [
    #prefixes
    '+# to Evasion Rating',
    '#% increased Rarity of Items found',
    '+# to maximum Life',
    #suffixes
    '+# to Dexterity',
],
'gloves': [
    #prefixes
    '+# to Evasion Rating',
    '#% increased Rarity of Items found',
    '#% of Physical Attack Damage Leeched as Mana',
    #suffixes
    '+# Life gained on Kill',
    '+#% to Chaos Resistance',
],
'helmet': [
    #prefixes
    '+# to Evasion Rating',
    '#% increased Rarity of Items found',
    '+# to maximum Life',
    #suffixes
    '+# to Dexterity',
    '+#% to Chaos Resistance',
    '#% increased Stun and Block Recovery',
],
'shield': [
    #prefixes
    '+# to maximum Life',
    '+# to maximum Mana',
    #suffixes
    '#% increased Mana Regeneration Rate',
    '+#% to Chaos Resistance',
    '+# Mana gained when you Block',
    '#% increased Cast Speed',
    '# Life Regenerated per second',
],
}
