ignore = {
    'ring': [
	#prefixes
	'+# to maximum Life',
	'Adds # to # Fire Damage to Attacks',
	'+# to maximum Mana',
	'+# to maximum Energy Shield',
	'#% of Physical Attack Damage Leeched as Mana',
	'+# to Evasion Rating',
	'Adds # to # Physical Damage to Attacks',
	'#% of Physical Attack Damage Leeched as Life',
	'Adds # to # Lightning Damage to Attacks',
	#suffixes
	'+#% to Chaos Resistance',
	'+# to all Attributes',
	'# Life Regenerated per second',
	'#% increased Fire Damage',
	'+#% to all Elemental Resistances',
	'#% increased Light Radius',
	'+#% to Cold Resistance',
	'+#% to Fire Resistance',
	'+# to Accuracy Rating',
	'#% increased Cast Speed',
	'+# Life gained on Kill',
	'#% increased Mana Regeneration Rate',
	'#% increased Attack Speed',
	'+#% to Lightning Resistance',
	'#% increased Lightning Damage',
	'+# to Strength',
    ],
    'amulet': [
	#prefixes
	'+# to maximum Life',
	'Adds # to # Fire Damage to Attacks',
	'+# to maximum Mana',
	'#% increased Evasion Rating',
	'+# to maximum Energy Shield',
	'#% of Physical Attack Damage Leeched as Mana',
	'Adds # to # Physical Damage to Attacks',
	'#% increased maximum Energy Shield',
	'#% increased Armour',
	'#% of Physical Attack Damage Leeched as Life',
	'Adds # to # Lightning Damage to Attacks',
	'+#% to Chaos Resistance',
	'+# to all Attributes',
	'#% increased Fire Damage',
	'+#% to all Elemental Resistances',
	'+# to Dexterity',
	'+# to Intelligence',
	'+#% to Cold Resistance',
	'+#% to Fire Resistance',
	'+# to Accuracy Rating',
	'#% increased Cast Speed',
	'+# Life gained on Kill',
	'#% increased Mana Regeneration Rate',
	'#% increased Global Critical Strike Chance',
	'+#% to Global Critical Strike Multiplier',
	'+#% to Lightning Resistance',
	'#% increased Lightning Damage',
	'+# to Strength',
        '# Life Regenerated per second',
    ],
    'sceptre': [
	#prefixes
	'Adds # to # Fire Damage',
	'Adds # to # Fire Damage to Spells',
	'#% increased Elemental Damage with Attack Skills',
	'#% increased Physical Damage',
	'Adds # to # Lightning Damage',
	'+# to Accuracy Rating',
	'Adds # to # Cold Damage',
	'+#% to Cold Damage over Time Multiplier',
	'#% of Physical Attack Damage Leeched as Mana',
	'Adds # to # Physical Damage',
	'Gain #% of Fire Damage as Extra Chaos Damage',
	'+# to maximum Mana',
	'#% of Physical Attack Damage Leeched as Life',
	'Adds # to # Chaos Damage',
	#suffixes
	'#% increased Fire Damage',
	'#% increased Stun Duration on Enemies',
	'#% increased Burning Damage',
	'+#% to Fire Resistance',
	'#% increased Attack Speed',
	'#% reduced Enemy Stun Threshold',
	'#% increased Lightning Damage',
	'+#% to Chaos Resistance',
	'#% increased Critical Strike Chance',
	'+# Life gained on Kill',
	'#% increased Cast Speed',
	'+# to Accuracy Rating',
	'+#% to Global Critical Strike Multiplier',
	'+#% to Lightning Resistance',
	'#% chance to Ignite',
	'+#% to Cold Resistance',
	'#% increased Mana Regeneration Rate',
	'+# to Intelligence',
	'+# to Strength',
    ],
    'wand': [
	#prefixes
	'Adds # to # Fire Damage',
	'Adds # to # Fire Damage to Spells',
	'#% increased Elemental Damage with Attack Skills',
	'#% increased Physical Damage',
	'+#% to Non-Ailment Chaos Damage over Time Multiplier',
	'Adds # to # Lightning Damage',
	'+# to Accuracy Rating',
	'Adds # to # Cold Damage',
	'#% of Physical Attack Damage Leeched as Mana',
	'Adds # to # Physical Damage',
	'Gain #% of Fire Damage as Extra Chaos Damage',
	'+# to maximum Mana',
	'#% of Physical Attack Damage Leeched as Life',
	'Adds # to # Chaos Damage',
	#suffixes
	'#% increased Fire Damage',
	'#% increased Stun Duration on Enemies',
	'#% increased Burning Damage',
	'#% increased Cold Damage',
	'#% chance to Shock',
	'#% increased Attack Speed',
	'#% increased Lightning Damage',
	'+#% to Chaos Resistance',
	'#% increased Critical Strike Chance',
	'+# Life gained on Kill',
	'#% increased Cast Speed',
	'+# to Accuracy Rating',
	'+#% to Global Critical Strike Multiplier',
	'+#% to Lightning Resistance',
	'#% chance to Ignite',
	'+#% to Cold Resistance',
	'+# to Intelligence',
	'#% increased Critical Strike Chance for Spells',
	'#% increased Projectile Speed',
	'#% increased Mana Regeneration Rate',
	'+#% to Fire Resistance',
    ],
    'boots': [
	#prefixes
	'+# to maximum Life',
	'+# to Evasion Rating',
	#suffixes
	'+#% to Chaos Resistance',
	'# Life Regenerated per second',
	'#% increased Stun and Block Recovery',
	'+#% to Fire Resistance',
	'+#% to Cold Resistance',
	'+# to Dexterity',
	'+#% to Lightning Resistance',
    ],
    'gloves': [
	#prefixes
	'+# to maximum Life',
	'Adds # to # Fire Damage to Attacks',
	'Adds # to # Cold Damage to Attacks',
	'#% of Physical Attack Damage Leeched as Mana',
	'+# to Evasion Rating',
	'Adds # to # Physical Damage to Attacks',
	'#% of Physical Attack Damage Leeched as Life',
	'Adds # to # Lightning Damage to Attacks',
	#suffixes
	'+#% to Chaos Resistance',
	'# Life Regenerated per second',
	'+#% to Cold Resistance',
	'+# to Dexterity',
	'+# to Accuracy Rating',
	'+# Life gained on Kill',
	'#% increased Attack Speed',
	'+#% to Fire Resistance',
	'+#% to Lightning Resistance',
    ],
    'helmet': [
	#prefixes
	'+# to maximum Life',
	'+# to Evasion Rating',
	'Reflects # Physical Damage to Melee Attackers',
	#suffixes
	'+#% to Chaos Resistance',
	'# Life Regenerated per second',
	'#% increased Stun and Block Recovery',
	'+#% to Fire Resistance',
	'+#% to Cold Resistance',
	'+# to Dexterity',
	'+# to Accuracy Rating',
	'+# to Intelligence',
	'+#% to Lightning Resistance',
]}
